services:
  glance:
    container_name: glance
    image: glanceapp/glance
      # Optionally, also mount docker socket if you want to use the docker containers widget
      - ./glance_config:/app/config
      - ./glance_assets:/app/assets
    ports:
      - 9080:8080
    env_file: .env
    restart: always
volumes:
  glance_config: {}
  glance_asset: {}
